### ISSUE TITLE
Settings Sync

### ISSUE THREAD

**Issue by LukaHarambasic** [crydotsnake/my-vscode-setup#1]
Hi,
there is a plugin called "[Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)" which lets you save your settings to a gist.

I like that you share your setup, but maybe you could provide a gist with Settings Sync to make that a lot easier for you and everybody who is interested :)

Cheers,
Luka

**Comment by crydotsnake** [comment]
Hello Dear Luka,
Thank you!. I will take a look at it! :).
